# SonarCloud Configuration

sonar.organization=michilldev
sonar.projectKey=MiChillDev_sqs-project

sonar.projectName=SQS Project
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

# Backend
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.java.source=21

# Frontend
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Exclusions
sonar.coverage.exclusions=\
  **/ChuckNorrisApplication.java,\
  **/config/**,\
  **/entity/**,\
  **/dto/**

sonar.exclusions=\
  **/target/**,\
  **/node_modules/**,\
  **/*.sql,\
  **/db/migration/**

sonar.test.inclusions=\
  **/*Test.java,\
  **/*Tests.java

