#!/bin/sh
set -e
root="$(cd "$(dirname "$0")/../.." && pwd)"
export SEED_ADMIN_USERNAME=$(cat "$root/.secrets/app_seed_admin_username")
export SEED_ADMIN_PASSWORD=$(cat "$root/.secrets/app_seed_admin_password")
exec "$@"
